apiVersion: v1
kind: Service
metadata:
  name: swiggy-service
spec:
  type: LoadBalancer   # ou NodePort si tu veux aussi tester via IP de nœud
  selector:
    app: swiggy-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
