apiVersion: v1
kind: Service
metadata:
  name: flask-service
  labels:
    app: flask-ci-cd
spec:
  type: LoadBalancer
  selector:
    app: flask-ci-cd
  ports:
    - name: http             # utilisé par le ServiceMonitor
      port: 80
      targetPort: 5000